// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/example/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/example/[id].get').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/example/[id].patch').default>>>>
    }
    '/api/example': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/example/index').default>>>>
    }
    '/api/healthz': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/healthz.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}